[package]
name = "client"
version = "0.1.0"
authors = ["tensor-programming <abeltensor@tensor-programming.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
midir = "0.6.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
